### ISSUE TITLE
Questions and suggestions!

### ISSUE THREAD

**Issue by Nekkok** [TheDeathlyCow/more-geodes#27]
Hello again! 

I'm trying to make diamond geodes more common since I disabled the ore blocks to make my modpack harder and I wanted to change their configured features. The wiki points to `geodes/worldgen/configured_feature/diamond_geode.json` but inside the mod there are only `loot_tables`, `advancements`, `tags `and `recipes` folders and with my limited knowledge I don't know how I can tweak them. 

Could you add those folders inside the mod or make a datapack including them? Also, it could be possible to change their sizes? And last but not least, I saw you are trying to make a new material called bismuth! Could you tell me/us more about it? And now to the suggestions! The echolocator it's a really cool item, but I've thought two new approaches to it:

- I found that the wave visual particle to tell you in which direction is the nearest geode sometimes collapses into the block if the echolocator is above it, which has been a problem to me more time than I'd like to tell. So what about a new particle that would be bigger in size or more particles that could point to the block?

- In a completely different way, what about echolocators highlighting mobs through walls? The concept that the warden can guide through its senses makes me think that it possibly uses echo shards to do this. So yeah, I know this isn't the original idea at all, but I wanted to share it with you.

And that's it! I really love your mod, it makes mining so much rewarding and satisfying when you find geodes. Thank you! : )

**Comment by TheDeathlyCow** [comment]
The path specified in the 'wiki' is where you would place the files to *override* the definitions of those features supplied by the mod. Because of how the Fabric biome API works, these features are actually defined in Java code. The configured features are defined [here](https://github.com/TheDeathlyCow/more-geodes/blob/main/src/main/java/com/github/thedeathlycow/moregeodes/features/ModConfiguredFeatures.java) and the placed features are defined [here](https://github.com/TheDeathlyCow/more-geodes/blob/main/src/main/java/com/github/thedeathlycow/moregeodes/features/ModPlacedFeatures.java). However, if you want a base to work off of, that can actually be found in the [Forge version here](https://github.com/TheDeathlyCow/more-geodes-reforged/tree/main/src/main/resources/data/geodes/worldgen). It should be exactly the same as the Fabric version. 

Also, there is an important distinction between configured features and placed features with regards to what you are trying to accomplish. *Configured* Features define how a feature looks - the blocks it uses, its size, etc. *Placed* Features define how a configured feature is placed, such as what biomes, what y-levels, and, relevant here, rarity. The best place for making these sorts of files is [Misode's datapack generator](https://misode.github.io/). Look for the worldgen/placed feature generator, and use the Amethyst Geode as a template (since that's what I tend to use as a starting point). Basically, if you want to change the diamond geode size, you'd do it in the configured feature; if you want to change its rarity, you'd do it in the placed feature. 

Quick summary though, if you want to override diamond geode rarity you would create a file in `data/geodes/worldgen/placed_features/diamond_geode.json`. Then configure the `chance` field in the `minecraft:rarity_filter` placement function. Lower chance = more common. The [Minecraft Commands](https://www.reddit.com/r/MinecraftCommands/) subreddit and Discord are excellent sources of information if you want to learn more about datapacks.  

Now with regards to your other questions/feedback:

Bismuth is a material thats found in geodes in real life and was suggested by a friend of mine who is actually somewhat familiar with geology. I have no idea what I'm actually going to do with it, my priorities right now is more focused on figuring out what Gypsum should do before Bismuth. However, I do have a couple of ideas for both of these materials: 

* Gypsum should be used to make decorative building blocks, like Quartz is. 
* Gypsum Spears as weaker, early game variants of the Trident. 
* Bismuth could be added to fireworks stars to make them rainbow-coloured.
* Bismuth could be used to add and remove the Enchantment glint from items. 
* From today's snapshot (23w04a): Bismuth and Gypsum trim materials for armour. 

 

The fact only one particle is shown by the Echo Locator is really more of a technical limitation than a design one. As I'm sure your aware, sculk sensors can only listen to one vibration at a time, and the same is true of the Echo Locator. I definitely would have preferred to have more. I'm not really sure of the best approach to fix your issue, since the particle itself is created by the vanilla sculk system and not something new I've created. 

Having the Echo Locator highlight mobs through walls is also an interesting idea. The bell already sort of does that with Raiders. The locator needs something that resonates to highlight, perhaps the Echo Locator could highlight mobs that are wearing armour?

**Comment by Nekkok** [comment]
Sorry it took me so long to answer. I will try to mess aroung with datapacks then, but it would be could to have something I could compare to, so I can know in which direction I should modify things, if that's possible please. 

Talking about bismuth, maybe it could have more uses! The main approach looks really cool (fireworks need more love), but some cosmetics around them could make them gleam it even more. I know you didn't ask me anything, but if I come up with any idea, I will let you know : ]

And the echolocator topic... Yes, it's true that bells have that mechanic, but as I see it, it's only raid related. My take on echo-locators (or echoing-forks in my mind) is as some sort of artifact/tool that could detect different things and should be used in the main hand that could break (this is, taking damage durability with each use). So with that in mind, there would be different tunning forks to detect diffetent things:

- Amethyst forks that work as geode detectors. They may highlight smooth basalt/calcite/geode blocks (can't decide which) through walls with a 8x8 chunk radius (or maybe more/less, I don't know, maybe a block radius would be better). The color border of the highlight would match the color of the geode blocks (if you decide to detect those instead of the smooth basalt/calcite blocks). This would encourage the use of amethyst and would be more useful as they are now. With the correct balance of the durability of these tools and the spawn number of the geodes, would make amethyst shine as everybody will use them to find diamonds. And on top of that, this could be the final touch for those like me who like to disable emerald/diamond/quartz ores, because it won't unbalance the game for players who still decide to have the ore blocks enabled.

- Echo forks then would be used to detect life, but if you like to have them a different behaviour from vanilla bells, they could have the risk to activate any sculk related block, and I mean that you could just straightly spawn a Warden with only a tune of this fork. Exploring caves then would be much dangerous for players that don't know if they could be a deep dark biome, but still using them could serve them to make strategies to detect ancient cities and dangerous mobs around them.

This are just some of my thoughts, but I have more of them. I try to find balance and the main way to start it is by making them straightly tools. I think, and please don't misinterpet me, that the echolocator as a block form has limitations as it is now, because the way it signals through walls. Maybe it can work, but I think highlighting is the way it needs to be really helpful in the player's adventures.

Hope you like some of my ideas and if you don't, don't worry because I really like this mod anyway. It's just me trying to make things in my head the way I think _it could make more sense_, but is your mod and I won't complain about it ever. Thank you in regards : )

**Comment by TheDeathlyCow** [comment]
> I will try to mess around with datapacks then, but it would be cool to have something I could compare to, so I can know in which direction I should modify things, if that's possible please.

The Forge version does provide an example. However, it has now been brought over to Fabric for 1.19.3, which you can view [here](https://github.com/TheDeathlyCow/more-geodes/tree/main/src/main/resources/data/geodes/worldgen). 

As for the rest, I think this discussion is best left for Discord, which I see that you have now joined.
