### ISSUE TITLE
Not so much an issue as asking permission

### ISSUE THREAD

**Issue by yamitami** [TheDeathlyCow/more-geodes#31]
I wasn't really sure where else to ask this, but I'd like to ask permission to upload a small resource pack for this mod. The emerald clusters set off my fiance's trypophobia (fear of holes) so I made a texture pack that tweaks it enough to avoid that. Would it be okay with you if I upload to CurseForge, probably both as a standalone and in a combined anti-trypophobia resource pack (so far it's just got the emeralds and nether wart in it).

Love the mod!

**Comment by TheDeathlyCow** [comment]
Yep you have my full permission to go ahead with uploading it! 
Generally speaking, resource packs do not contain original files from the mods, and they require that the original mod be installed anyway in order to work. So, even the most restrictive of licenses should still allow for resource pack making without the need to get permission, but I appreciate it anyway!

**Comment by yamitami** [comment]
Thanks! By the way I couldn't possibly play without your mod, it's one of those forever installs regardless of pack. Keep up the excellent work!
